# Generated by Django 5.0.2 on 2024-02-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='Address',
            new_name='address',
        ),
    ]
