# Generated by Django 5.0.2 on 2024-02-16 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_rename_address_college_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('college_serial_no', models.IntegerField()),
                ('no_of_projects', models.IntegerField(default=0)),
                ('college_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college')),
                ('user_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
