# Generated by Django 5.0.2 on 2024-02-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='year',
            new_name='course_year',
        ),
    ]
