# Generated by Django 5.0.2 on 2024-02-16 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_rename_year_student_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
