# Generated by Django 5.0.2 on 2024-02-17 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_alter_college_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('member_details_1', models.CharField(max_length=100)),
                ('member_details_2', models.CharField(max_length=100)),
                ('member_details_3', models.CharField(max_length=100)),
                ('member_details_4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_domain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='college.domain')),
            ],
        ),
    ]
